version: '3'
services:
  db:
    image: postgres:11.8-alpine
    environment:
      - POSTGRES_USER=cluster
      - POSTGRES_PASSWORD=${PG_PASS}
      - POSTGRES_DB=cluster

  db-update:
    build: ../liquibase
    volumes:
      - ./db-patches:/db-patches
    depends_on:
      - db
    command: >-
      liquibase
        --url=jdbc:postgresql://db/cluster
        --classpath=/usr/bin/postgresql.jar:/db-patches/
        --changeLogFile=changelog.yaml
        --logLevel=info
        --username=cluster
        --password=${PG_PASS}
        update

  db-rollback:
    build: ../liquibase
    volumes:
      - ./db-patches:/db-patches
    depends_on:
      - db
    command: >-
      liquibase
        --url=jdbc:postgresql://db/cluster
        --classpath=/usr/bin/postgresql.jar:/db-patches/
        --changeLogFile=changelog.yaml
        --logLevel=info
        --username=cluster
        --password=${PG_PASS}
        rollbackCount 1
  